#!/bin/bash
set -e

# Bron Vault VM Setup Script
# This script installs Docker, configures the environment, and starts the application.

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}=====================================================${NC}"
echo -e "${GREEN}       Bron Vault - VM Setup & Deployment            ${NC}"
echo -e "${GREEN}=====================================================${NC}"

# Check for root/sudo
if [ "$EUID" -ne 0 ]; then
  echo -e "${YELLOW}Please run as root or use sudo.${NC}"
  exit 1
fi

# -----------------------------------------------------------
# 1. Install Docker & Docker Compose (if missing)
# -----------------------------------------------------------
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Docker not found. Installing Docker...${NC}"
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    echo -e "${GREEN}Docker installed successfully.${NC}"
else
    echo -e "${GREEN}Docker is already installed.${NC}"
fi

# Ensure Docker service is running
systemctl enable docker
systemctl start docker

# Check for Docker Compose (V2 plugin)
if ! docker compose version &> /dev/null; then
    echo -e "${YELLOW}Docker Compose plugin not found. Attempting to install plugin...${NC}"
    apt-get update && apt-get install -y docker-compose-plugin
    if ! docker compose version &> /dev/null; then
         echo -e "${RED}Failed to install Docker Compose. Please install it manually.${NC}"
         exit 1
    fi
fi

# -----------------------------------------------------------
# 2. Configuration & .env Generation
# -----------------------------------------------------------
echo -e "\n${YELLOW}--- Configuration Setup ---${NC}"

# Database Password
read -s -p "Enter a secure Database Password (leave blank to generate one): " DB_PASSWORD
echo ""
if [ -z "$DB_PASSWORD" ]; then
    DB_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9')
    echo -e "Generated Database Password: ${GREEN}$DB_PASSWORD${NC}"
fi

# SingleStore License & Image Selection
echo -e "\n${YELLOW}SingleStore Configuration:${NC}"
echo "1. Use 'singlestore/cluster-in-a-box' (Requires License Key)"
echo "2. Use 'singlestore-labs/singlestoredb-dev' (Free for Dev/Test, No License Required)"
read -p "Select option [1/2] (Default: 2 if no license): " SS_OPTION

SINGLESTORE_LICENSE=""
SINGLESTORE_IMAGE="ghcr.io/singlestore-labs/singlestoredb-dev:latest"

if [ "$SS_OPTION" == "1" ]; then
    read -p "Enter your SingleStore License Key: " SINGLESTORE_LICENSE
    if [ -z "$SINGLESTORE_LICENSE" ]; then
        echo -e "${RED}Error: License key is required for Option 1.${NC}"
        echo "Falling back to Developer Image (Option 2)..."
    else
        SINGLESTORE_IMAGE="singlestore/cluster-in-a-box:latest"
    fi
elif [ "$SS_OPTION" == "2" ]; then
     echo "Using Developer Image (No License Required)."
else
    # Default behavior: Ask for license, if empty -> use dev image
    read -p "Enter SingleStore License Key (Leave blank to use Free/Dev image): " SINGLESTORE_LICENSE
    if [ -n "$SINGLESTORE_LICENSE" ]; then
        SINGLESTORE_IMAGE="singlestore/cluster-in-a-box:latest"
    else
        echo "No license provided. Using Developer Image."
    fi
fi

# JWT Secret
JWT_SECRET=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9')

# Write .env file
echo -e "\n${YELLOW}Generating .env file...${NC}"

cat > .env <<EOF
# Generated by setup-vm.sh
SINGLESTORE_IMAGE=$SINGLESTORE_IMAGE
SINGLESTORE_LICENSE_KEY=$SINGLESTORE_LICENSE
MYSQL_PASSWORD=$DB_PASSWORD
MYSQL_DATABASE=bronvaultnew
REDIS_URL=redis://redis:6379
JWT_SECRET=$JWT_SECRET
NEXT_PUBLIC_ENABLE_AUTH=true
NODE_ENV=production
EOF

echo -e "${GREEN}.env file created successfully.${NC}"

# -----------------------------------------------------------
# 3. Deployment
# -----------------------------------------------------------
echo -e "\n${YELLOW}--- Starting Services ---${NC}"
echo "Pulling images and building containers..."

docker compose up -d --build

echo -e "\n${GREEN}=====================================================${NC}"
echo -e "${GREEN}       Deployment Complete!                          ${NC}"
echo -e "${GREEN}=====================================================${NC}"
echo -e "App is running on port 3000"
echo -e "SingleStore is running on port 3306 (SQL) and 8080 (Studio)"
echo -e "DB Password: ${YELLOW}$DB_PASSWORD${NC}"
echo -e "Configuration saved to .env"
